FROM deathstarbench/social-network-microservices

COPY ./ComposePostService/build/ComposePostService /usr/local/bin/ComposePostService
COPY ./HomeTimelineService/build/HomeTimelineService /usr/local/bin/HomeTimelineService
COPY ./MediaService/build/MediaService /usr/local/bin/MediaService
COPY ./PostStorageService/build/PostStorageService /usr/local/bin/PostStorageService
COPY ./SocialGraphService/build/SocialGraphService /usr/local/bin/SocialGraphService
COPY ./TextService/build/TextService /usr/local/bin/TextService
COPY ./UniqueIdService/build/UniqueIdService /usr/local/bin/UniqueIdService
COPY ./UrlShortenService/build/UrlShortenService /usr/local/bin/UrlShortenService
COPY ./UserMentionService/build/UserMentionService /usr/local/bin/UserMentionService
COPY ./UserService/build/UserService /usr/local/bin/UserService
COPY ./UserTimelineService/build/UserTimelineService /usr/local/bin/UserTimelineService
COPY ./WriteHomeTimelineService/build/WriteHomeTimelineService /usr/local/bin/WriteHomeTimelineService